{
	"id": "RLSA-2021:1608",
	"advisories": [
		{
			"content": {
				"id": "RLSA-2021:1608",
				"title": "Moderate: python-cryptography security, bug fix, and enhancement update",
				"description": "The python-cryptography packages contain a Python Cryptographic Authority's (PyCA's) cryptography library, which provides cryptographic primitives and recipes to Python developers.\n\nThe following packages have been upgraded to a later upstream version: python-cryptography (3.2.1). (BZ#1873581, BZ#1891947)\n\nSecurity Fix(es):\n\n* python-cryptography: bleichenbacher timing oracle attack against RSA decryption (CVE-2020-25659)\n\n* python-cryptography: certain sequences of update() calls when symmetrically encrypting very large payloads could result in an integer overflow and lead to buffer overflows (CVE-2020-36242)\n\nFor more details about the security issue(s), including the impact, a CVSS score, acknowledgments, and other related information, refer to the CVE page(s) listed in the References section.\n\nAdditional Changes:\n\nFor detailed information on changes in this release, see the Rocky Linux 8.4 Release Notes linked from the References section.",
				"severity": [
					{
						"type": "vendor",
						"source": "errata.rockylinux.org",
						"vendor": "MODERATE"
					}
				],
				"references": [
					{
						"source": "MITRE",
						"url": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-25659"
					},
					{
						"source": "MITRE",
						"url": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-36242"
					},
					{
						"source": "Red Hat",
						"url": "https://bugzilla.redhat.com/show_bug.cgi?id=1778939"
					},
					{
						"source": "Red Hat",
						"url": "https://bugzilla.redhat.com/show_bug.cgi?id=1873581"
					},
					{
						"source": "Red Hat",
						"url": "https://bugzilla.redhat.com/show_bug.cgi?id=1889988"
					},
					{
						"source": "Red Hat",
						"url": "https://bugzilla.redhat.com/show_bug.cgi?id=1891947"
					},
					{
						"source": "Red Hat",
						"url": "https://bugzilla.redhat.com/show_bug.cgi?id=1907429"
					},
					{
						"source": "Red Hat",
						"url": "https://bugzilla.redhat.com/show_bug.cgi?id=1926226"
					},
					{
						"source": "errata.rockylinux.org",
						"url": "https://errata.rockylinux.org/RLSA-2021:1608"
					}
				],
				"published": "2021-05-18T05:38:36Z"
			},
			"segments": [
				{
					"ecosystem": "rocky:8"
				}
			]
		}
	],
	"vulnerabilities": [
		{
			"content": {
				"id": "CVE-2020-25659",
				"severity": [
					{
						"type": "cvss_v31",
						"source": "MITRE",
						"cvss_v31": {
							"vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:N/A:N",
							"base_score": 5.9,
							"base_severity": "MEDIUM",
							"temporal_score": 5.9,
							"temporal_severity": "MEDIUM",
							"environmental_score": 5.9,
							"environmental_severity": "MEDIUM"
						}
					}
				],
				"cwe": [
					{
						"source": "MITRE",
						"cwe": [
							"CWE-385"
						]
					}
				],
				"references": [
					{
						"source": "MITRE",
						"url": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-25659"
					}
				]
			},
			"segments": [
				{
					"ecosystem": "rocky:8"
				}
			]
		},
		{
			"content": {
				"id": "CVE-2020-36242",
				"severity": [
					{
						"type": "cvss_v31",
						"source": "MITRE",
						"cvss_v31": {
							"vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:H",
							"base_score": 8.2,
							"base_severity": "HIGH",
							"temporal_score": 8.2,
							"temporal_severity": "HIGH",
							"environmental_score": 8.2,
							"environmental_severity": "HIGH"
						}
					}
				],
				"cwe": [
					{
						"source": "MITRE",
						"cwe": [
							"CWE-190->CWE-119"
						]
					}
				],
				"references": [
					{
						"source": "MITRE",
						"url": "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-36242"
					}
				]
			},
			"segments": [
				{
					"ecosystem": "rocky:8"
				}
			]
		}
	],
	"detections": [
		{
			"ecosystem": "rocky:8",
			"conditions": [
				{
					"criteria": {
						"operator": "OR",
						"criterions": [
							{
								"type": "version",
								"version": {
									"vulnerable": true,
									"fix_status": {
										"class": "fixed"
									},
									"package": {
										"name": "python-cryptography-debugsource",
										"architectures": [
											"aarch64",
											"x86_64"
										]
									},
									"affected": {
										"type": "rpm",
										"range": [
											{
												"lt": "0:3.2.1-4.el8"
											}
										],
										"fixed": [
											"0:3.2.1-4.el8"
										]
									}
								}
							},
							{
								"type": "version",
								"version": {
									"vulnerable": true,
									"fix_status": {
										"class": "fixed"
									},
									"package": {
										"name": "python3-cryptography",
										"architectures": [
											"aarch64",
											"x86_64"
										]
									},
									"affected": {
										"type": "rpm",
										"range": [
											{
												"lt": "0:3.2.1-4.el8"
											}
										],
										"fixed": [
											"0:3.2.1-4.el8"
										]
									}
								}
							},
							{
								"type": "version",
								"version": {
									"vulnerable": true,
									"fix_status": {
										"class": "fixed"
									},
									"package": {
										"name": "python3-cryptography-debuginfo",
										"architectures": [
											"aarch64",
											"x86_64"
										]
									},
									"affected": {
										"type": "rpm",
										"range": [
											{
												"lt": "0:3.2.1-4.el8"
											}
										],
										"fixed": [
											"0:3.2.1-4.el8"
										]
									}
								}
							}
						]
					}
				}
			]
		}
	],
	"data_source": {
		"id": "rocky-errata",
		"raws": [
			"vuls-data-raw-rocky-errata/2021/RLSA-2021:1608.json"
		]
	}
}
